/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ViewActivityMeasuresMeasureType implements EnumType {

    integer("integer"),

    decimal("decimal"),

    single_cat("single_cat"),

    multi_cat("multi_cat"),

    date("date"),

    text("text"),

    truth_value("truth_value");

    private final String literal;

    private ViewActivityMeasuresMeasureType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "view_activity_measures_measure_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ViewActivityMeasuresMeasureType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ViewActivityMeasuresMeasureType.class, literal);
    }
    // @formatter:on
}
