/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.tables.ActivityTypes;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityTypesRecord extends UpdatableRecordImpl<ActivityTypesRecord> implements Record5<Integer, String, byte[], Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tractivity_db.activity_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tractivity_db.activity_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.activity_types.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.activity_types.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tractivity_db.activity_types.image</code>.
     */
    public void setImage(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>tractivity_db.activity_types.image</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>tractivity_db.activity_types.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>tractivity_db.activity_types.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>tractivity_db.activity_types.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tractivity_db.activity_types.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, byte[], Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, byte[], Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ActivityTypes.ACTIVITY_TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return ActivityTypes.ACTIVITY_TYPES.NAME;
    }

    @Override
    public Field<byte[]> field3() {
        return ActivityTypes.ACTIVITY_TYPES.IMAGE;
    }

    @Override
    public Field<Timestamp> field4() {
        return ActivityTypes.ACTIVITY_TYPES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return ActivityTypes.ACTIVITY_TYPES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public byte[] component3() {
        return getImage();
    }

    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public byte[] value3() {
        return getImage();
    }

    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    @Override
    public ActivityTypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ActivityTypesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActivityTypesRecord value3(byte[] value) {
        setImage(value);
        return this;
    }

    @Override
    public ActivityTypesRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ActivityTypesRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ActivityTypesRecord values(Integer value1, String value2, byte[] value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityTypesRecord
     */
    public ActivityTypesRecord() {
        super(ActivityTypes.ACTIVITY_TYPES);
    }

    /**
     * Create a detached, initialised ActivityTypesRecord
     */
    public ActivityTypesRecord(Integer id, String name, byte[] image, Timestamp createdOn, Timestamp updatedOn) {
        super(ActivityTypes.ACTIVITY_TYPES);

        setId(id);
        setName(name);
        setImage(image);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ActivityTypesRecord
     */
    public ActivityTypesRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.ActivityTypes value) {
        super(ActivityTypes.ACTIVITY_TYPES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setImage(value.getImage());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
