/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.tables.Locations;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationsRecord extends UpdatableRecordImpl<LocationsRecord> implements Record7<Integer, String, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tractivity_db.locations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.locations.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tractivity_db.locations.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>tractivity_db.locations.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>tractivity_db.locations.elevation</code>.
     */
    public void setElevation(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.elevation</code>.
     */
    public BigDecimal getElevation() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>tractivity_db.locations.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>tractivity_db.locations.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tractivity_db.locations.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Locations.LOCATIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Locations.LOCATIONS.NAME;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Locations.LOCATIONS.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Locations.LOCATIONS.LONGITUDE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Locations.LOCATIONS.ELEVATION;
    }

    @Override
    public Field<Timestamp> field6() {
        return Locations.LOCATIONS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field7() {
        return Locations.LOCATIONS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public BigDecimal component3() {
        return getLatitude();
    }

    @Override
    public BigDecimal component4() {
        return getLongitude();
    }

    @Override
    public BigDecimal component5() {
        return getElevation();
    }

    @Override
    public Timestamp component6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component7() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public BigDecimal value3() {
        return getLatitude();
    }

    @Override
    public BigDecimal value4() {
        return getLongitude();
    }

    @Override
    public BigDecimal value5() {
        return getElevation();
    }

    @Override
    public Timestamp value6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value7() {
        return getUpdatedOn();
    }

    @Override
    public LocationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LocationsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LocationsRecord value3(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public LocationsRecord value4(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public LocationsRecord value5(BigDecimal value) {
        setElevation(value);
        return this;
    }

    @Override
    public LocationsRecord value6(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public LocationsRecord value7(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public LocationsRecord values(Integer value1, String value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationsRecord
     */
    public LocationsRecord() {
        super(Locations.LOCATIONS);
    }

    /**
     * Create a detached, initialised LocationsRecord
     */
    public LocationsRecord(Integer id, String name, BigDecimal latitude, BigDecimal longitude, BigDecimal elevation, Timestamp createdOn, Timestamp updatedOn) {
        super(Locations.LOCATIONS);

        setId(id);
        setName(name);
        setLatitude(latitude);
        setLongitude(longitude);
        setElevation(elevation);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised LocationsRecord
     */
    public LocationsRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.Locations value) {
        super(Locations.LOCATIONS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setElevation(value.getElevation());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
