/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.enums.MeasuresType;
import uk.co.raubach.tractivity.server.database.codegen.tables.Measures;
import uk.co.raubach.tractivity.server.pojo.MeasureRestrictions;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasuresRecord extends UpdatableRecordImpl<MeasuresRecord> implements Record7<Integer, String, MeasuresType, byte[], MeasureRestrictions, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tractivity_db.measures.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.measures.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tractivity_db.measures.type</code>.
     */
    public void setType(MeasuresType value) {
        set(2, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.type</code>.
     */
    public MeasuresType getType() {
        return (MeasuresType) get(2);
    }

    /**
     * Setter for <code>tractivity_db.measures.image</code>.
     */
    public void setImage(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.image</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>tractivity_db.measures.restrictions</code>.
     */
    public void setRestrictions(MeasureRestrictions value) {
        set(4, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.restrictions</code>.
     */
    public MeasureRestrictions getRestrictions() {
        return (MeasureRestrictions) get(4);
    }

    /**
     * Setter for <code>tractivity_db.measures.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>tractivity_db.measures.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tractivity_db.measures.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, MeasuresType, byte[], MeasureRestrictions, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, MeasuresType, byte[], MeasureRestrictions, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Measures.MEASURES.ID;
    }

    @Override
    public Field<String> field2() {
        return Measures.MEASURES.NAME;
    }

    @Override
    public Field<MeasuresType> field3() {
        return Measures.MEASURES.TYPE;
    }

    @Override
    public Field<byte[]> field4() {
        return Measures.MEASURES.IMAGE;
    }

    @Override
    public Field<MeasureRestrictions> field5() {
        return Measures.MEASURES.RESTRICTIONS;
    }

    @Override
    public Field<Timestamp> field6() {
        return Measures.MEASURES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field7() {
        return Measures.MEASURES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public MeasuresType component3() {
        return getType();
    }

    @Override
    public byte[] component4() {
        return getImage();
    }

    @Override
    public MeasureRestrictions component5() {
        return getRestrictions();
    }

    @Override
    public Timestamp component6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component7() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public MeasuresType value3() {
        return getType();
    }

    @Override
    public byte[] value4() {
        return getImage();
    }

    @Override
    public MeasureRestrictions value5() {
        return getRestrictions();
    }

    @Override
    public Timestamp value6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value7() {
        return getUpdatedOn();
    }

    @Override
    public MeasuresRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MeasuresRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MeasuresRecord value3(MeasuresType value) {
        setType(value);
        return this;
    }

    @Override
    public MeasuresRecord value4(byte[] value) {
        setImage(value);
        return this;
    }

    @Override
    public MeasuresRecord value5(MeasureRestrictions value) {
        setRestrictions(value);
        return this;
    }

    @Override
    public MeasuresRecord value6(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public MeasuresRecord value7(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public MeasuresRecord values(Integer value1, String value2, MeasuresType value3, byte[] value4, MeasureRestrictions value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeasuresRecord
     */
    public MeasuresRecord() {
        super(Measures.MEASURES);
    }

    /**
     * Create a detached, initialised MeasuresRecord
     */
    public MeasuresRecord(Integer id, String name, MeasuresType type, byte[] image, MeasureRestrictions restrictions, Timestamp createdOn, Timestamp updatedOn) {
        super(Measures.MEASURES);

        setId(id);
        setName(name);
        setType(type);
        setImage(image);
        setRestrictions(restrictions);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised MeasuresRecord
     */
    public MeasuresRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.Measures value) {
        super(Measures.MEASURES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setType(value.getType());
            setImage(value.getImage());
            setRestrictions(value.getRestrictions());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
