/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.tables.ViewActivityParticipantMeasures;
import uk.co.raubach.tractivity.server.pojo.ParticipantMeasures;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewActivityParticipantMeasuresRecord extends TableRecordImpl<ViewActivityParticipantMeasuresRecord> implements Record13<Integer, Integer, String, Timestamp, Integer, String, Timestamp, Integer, String, BigDecimal, BigDecimal, BigDecimal, ParticipantMeasures[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_name</code>.
     */
    public void setActivityTypeName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_name</code>.
     */
    public String getActivityTypeName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_created_on</code>.
     */
    public void setActivityCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_created_on</code>.
     */
    public Timestamp getActivityCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_name</code>.
     */
    public void setEventName(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_name</code>.
     */
    public String getEventName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_created_on</code>.
     */
    public void setEventCreatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_created_on</code>.
     */
    public Timestamp getEventCreatedOn() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_name</code>.
     */
    public void setLocationName(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_name</code>.
     */
    public String getLocationName() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_latitude</code>.
     */
    public void setLocationLatitude(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_latitude</code>.
     */
    public BigDecimal getLocationLatitude() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_longitude</code>.
     */
    public void setLocationLongitude(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_longitude</code>.
     */
    public BigDecimal getLocationLongitude() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_elevation</code>.
     */
    public void setLocationElevation(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_elevation</code>.
     */
    public BigDecimal getLocationElevation() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.participant_measures</code>.
     */
    public void setParticipantMeasures(ParticipantMeasures[] value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.participant_measures</code>.
     */
    public ParticipantMeasures[] getParticipantMeasures() {
        return (ParticipantMeasures[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, String, Timestamp, Integer, String, Timestamp, Integer, String, BigDecimal, BigDecimal, BigDecimal, ParticipantMeasures[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, String, Timestamp, Integer, String, Timestamp, Integer, String, BigDecimal, BigDecimal, BigDecimal, ParticipantMeasures[]> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.ACTIVITY_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.ACTIVITY_TYPE_ID;
    }

    @Override
    public Field<String> field3() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.ACTIVITY_TYPE_NAME;
    }

    @Override
    public Field<Timestamp> field4() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.ACTIVITY_CREATED_ON;
    }

    @Override
    public Field<Integer> field5() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.EVENT_ID;
    }

    @Override
    public Field<String> field6() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.EVENT_NAME;
    }

    @Override
    public Field<Timestamp> field7() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.EVENT_CREATED_ON;
    }

    @Override
    public Field<Integer> field8() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.LOCATION_ID;
    }

    @Override
    public Field<String> field9() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.LOCATION_NAME;
    }

    @Override
    public Field<BigDecimal> field10() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.LOCATION_LATITUDE;
    }

    @Override
    public Field<BigDecimal> field11() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.LOCATION_LONGITUDE;
    }

    @Override
    public Field<BigDecimal> field12() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.LOCATION_ELEVATION;
    }

    @Override
    public Field<ParticipantMeasures[]> field13() {
        return ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES.PARTICIPANT_MEASURES;
    }

    @Override
    public Integer component1() {
        return getActivityId();
    }

    @Override
    public Integer component2() {
        return getActivityTypeId();
    }

    @Override
    public String component3() {
        return getActivityTypeName();
    }

    @Override
    public Timestamp component4() {
        return getActivityCreatedOn();
    }

    @Override
    public Integer component5() {
        return getEventId();
    }

    @Override
    public String component6() {
        return getEventName();
    }

    @Override
    public Timestamp component7() {
        return getEventCreatedOn();
    }

    @Override
    public Integer component8() {
        return getLocationId();
    }

    @Override
    public String component9() {
        return getLocationName();
    }

    @Override
    public BigDecimal component10() {
        return getLocationLatitude();
    }

    @Override
    public BigDecimal component11() {
        return getLocationLongitude();
    }

    @Override
    public BigDecimal component12() {
        return getLocationElevation();
    }

    @Override
    public ParticipantMeasures[] component13() {
        return getParticipantMeasures();
    }

    @Override
    public Integer value1() {
        return getActivityId();
    }

    @Override
    public Integer value2() {
        return getActivityTypeId();
    }

    @Override
    public String value3() {
        return getActivityTypeName();
    }

    @Override
    public Timestamp value4() {
        return getActivityCreatedOn();
    }

    @Override
    public Integer value5() {
        return getEventId();
    }

    @Override
    public String value6() {
        return getEventName();
    }

    @Override
    public Timestamp value7() {
        return getEventCreatedOn();
    }

    @Override
    public Integer value8() {
        return getLocationId();
    }

    @Override
    public String value9() {
        return getLocationName();
    }

    @Override
    public BigDecimal value10() {
        return getLocationLatitude();
    }

    @Override
    public BigDecimal value11() {
        return getLocationLongitude();
    }

    @Override
    public BigDecimal value12() {
        return getLocationElevation();
    }

    @Override
    public ParticipantMeasures[] value13() {
        return getParticipantMeasures();
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value1(Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value2(Integer value) {
        setActivityTypeId(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value3(String value) {
        setActivityTypeName(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value4(Timestamp value) {
        setActivityCreatedOn(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value5(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value6(String value) {
        setEventName(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value7(Timestamp value) {
        setEventCreatedOn(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value8(Integer value) {
        setLocationId(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value9(String value) {
        setLocationName(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value10(BigDecimal value) {
        setLocationLatitude(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value11(BigDecimal value) {
        setLocationLongitude(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value12(BigDecimal value) {
        setLocationElevation(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord value13(ParticipantMeasures[] value) {
        setParticipantMeasures(value);
        return this;
    }

    @Override
    public ViewActivityParticipantMeasuresRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Integer value5, String value6, Timestamp value7, Integer value8, String value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, ParticipantMeasures[] value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewActivityParticipantMeasuresRecord
     */
    public ViewActivityParticipantMeasuresRecord() {
        super(ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES);
    }

    /**
     * Create a detached, initialised ViewActivityParticipantMeasuresRecord
     */
    public ViewActivityParticipantMeasuresRecord(Integer activityId, Integer activityTypeId, String activityTypeName, Timestamp activityCreatedOn, Integer eventId, String eventName, Timestamp eventCreatedOn, Integer locationId, String locationName, BigDecimal locationLatitude, BigDecimal locationLongitude, BigDecimal locationElevation, ParticipantMeasures[] participantMeasures) {
        super(ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES);

        setActivityId(activityId);
        setActivityTypeId(activityTypeId);
        setActivityTypeName(activityTypeName);
        setActivityCreatedOn(activityCreatedOn);
        setEventId(eventId);
        setEventName(eventName);
        setEventCreatedOn(eventCreatedOn);
        setLocationId(locationId);
        setLocationName(locationName);
        setLocationLatitude(locationLatitude);
        setLocationLongitude(locationLongitude);
        setLocationElevation(locationElevation);
        setParticipantMeasures(participantMeasures);
    }

    /**
     * Create a detached, initialised ViewActivityParticipantMeasuresRecord
     */
    public ViewActivityParticipantMeasuresRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.ViewActivityParticipantMeasures value) {
        super(ViewActivityParticipantMeasures.VIEW_ACTIVITY_PARTICIPANT_MEASURES);

        if (value != null) {
            setActivityId(value.getActivityId());
            setActivityTypeId(value.getActivityTypeId());
            setActivityTypeName(value.getActivityTypeName());
            setActivityCreatedOn(value.getActivityCreatedOn());
            setEventId(value.getEventId());
            setEventName(value.getEventName());
            setEventCreatedOn(value.getEventCreatedOn());
            setLocationId(value.getLocationId());
            setLocationName(value.getLocationName());
            setLocationLatitude(value.getLocationLatitude());
            setLocationLongitude(value.getLocationLongitude());
            setLocationElevation(value.getLocationElevation());
            setParticipantMeasures(value.getParticipantMeasures());
        }
    }
    // @formatter:on
}
