/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.tables.ViewActivities;
import uk.co.raubach.tractivity.server.pojo.SimpleParticipant;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewActivitiesRecord extends TableRecordImpl<ViewActivitiesRecord> implements Record8<Integer, Integer, String, Timestamp, Integer, String, Timestamp, SimpleParticipant[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tractivity_db.view_activities.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.activity_type_name</code>.
     */
    public void setActivityTypeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.activity_type_name</code>.
     */
    public String getActivityTypeName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activities.activity_created_on</code>.
     */
    public void setActivityCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activities.activity_created_on</code>.
     */
    public Timestamp getActivityCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.event_name</code>.
     */
    public void setEventName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.event_name</code>.
     */
    public String getEventName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.event_created_on</code>.
     */
    public void setEventCreatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.event_created_on</code>.
     */
    public Timestamp getEventCreatedOn() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>tractivity_db.view_activities.participants</code>.
     */
    public void setParticipants(SimpleParticipant[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activities.participants</code>.
     */
    public SimpleParticipant[] getParticipants() {
        return (SimpleParticipant[]) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, Timestamp, Integer, String, Timestamp, SimpleParticipant[]> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, Timestamp, Integer, String, Timestamp, SimpleParticipant[]> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewActivities.VIEW_ACTIVITIES.ACTIVITY_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ViewActivities.VIEW_ACTIVITIES.ACTIVITY_TYPE_ID;
    }

    @Override
    public Field<String> field3() {
        return ViewActivities.VIEW_ACTIVITIES.ACTIVITY_TYPE_NAME;
    }

    @Override
    public Field<Timestamp> field4() {
        return ViewActivities.VIEW_ACTIVITIES.ACTIVITY_CREATED_ON;
    }

    @Override
    public Field<Integer> field5() {
        return ViewActivities.VIEW_ACTIVITIES.EVENT_ID;
    }

    @Override
    public Field<String> field6() {
        return ViewActivities.VIEW_ACTIVITIES.EVENT_NAME;
    }

    @Override
    public Field<Timestamp> field7() {
        return ViewActivities.VIEW_ACTIVITIES.EVENT_CREATED_ON;
    }

    @Override
    public Field<SimpleParticipant[]> field8() {
        return ViewActivities.VIEW_ACTIVITIES.PARTICIPANTS;
    }

    @Override
    public Integer component1() {
        return getActivityId();
    }

    @Override
    public Integer component2() {
        return getActivityTypeId();
    }

    @Override
    public String component3() {
        return getActivityTypeName();
    }

    @Override
    public Timestamp component4() {
        return getActivityCreatedOn();
    }

    @Override
    public Integer component5() {
        return getEventId();
    }

    @Override
    public String component6() {
        return getEventName();
    }

    @Override
    public Timestamp component7() {
        return getEventCreatedOn();
    }

    @Override
    public SimpleParticipant[] component8() {
        return getParticipants();
    }

    @Override
    public Integer value1() {
        return getActivityId();
    }

    @Override
    public Integer value2() {
        return getActivityTypeId();
    }

    @Override
    public String value3() {
        return getActivityTypeName();
    }

    @Override
    public Timestamp value4() {
        return getActivityCreatedOn();
    }

    @Override
    public Integer value5() {
        return getEventId();
    }

    @Override
    public String value6() {
        return getEventName();
    }

    @Override
    public Timestamp value7() {
        return getEventCreatedOn();
    }

    @Override
    public SimpleParticipant[] value8() {
        return getParticipants();
    }

    @Override
    public ViewActivitiesRecord value1(Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value2(Integer value) {
        setActivityTypeId(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value3(String value) {
        setActivityTypeName(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value4(Timestamp value) {
        setActivityCreatedOn(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value5(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value6(String value) {
        setEventName(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value7(Timestamp value) {
        setEventCreatedOn(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord value8(SimpleParticipant[] value) {
        setParticipants(value);
        return this;
    }

    @Override
    public ViewActivitiesRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Integer value5, String value6, Timestamp value7, SimpleParticipant[] value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewActivitiesRecord
     */
    public ViewActivitiesRecord() {
        super(ViewActivities.VIEW_ACTIVITIES);
    }

    /**
     * Create a detached, initialised ViewActivitiesRecord
     */
    public ViewActivitiesRecord(Integer activityId, Integer activityTypeId, String activityTypeName, Timestamp activityCreatedOn, Integer eventId, String eventName, Timestamp eventCreatedOn, SimpleParticipant[] participants) {
        super(ViewActivities.VIEW_ACTIVITIES);

        setActivityId(activityId);
        setActivityTypeId(activityTypeId);
        setActivityTypeName(activityTypeName);
        setActivityCreatedOn(activityCreatedOn);
        setEventId(eventId);
        setEventName(eventName);
        setEventCreatedOn(eventCreatedOn);
        setParticipants(participants);
    }

    /**
     * Create a detached, initialised ViewActivitiesRecord
     */
    public ViewActivitiesRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.ViewActivities value) {
        super(ViewActivities.VIEW_ACTIVITIES);

        if (value != null) {
            setActivityId(value.getActivityId());
            setActivityTypeId(value.getActivityTypeId());
            setActivityTypeName(value.getActivityTypeName());
            setActivityCreatedOn(value.getActivityCreatedOn());
            setEventId(value.getEventId());
            setEventName(value.getEventName());
            setEventCreatedOn(value.getEventCreatedOn());
            setParticipants(value.getParticipants());
        }
    }
    // @formatter:on
}
