/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.tables.ViewEvents;
import uk.co.raubach.tractivity.server.pojo.SimpleActivity;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewEventsRecord extends TableRecordImpl<ViewEventsRecord> implements Record6<Integer, String, String, Timestamp, Timestamp, SimpleActivity[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tractivity_db.view_events.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_name</code>.
     */
    public void setEventName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_name</code>.
     */
    public String getEventName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_description</code>.
     */
    public void setEventDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_description</code>.
     */
    public String getEventDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_created_on</code>.
     */
    public void setEventCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_created_on</code>.
     */
    public Timestamp getEventCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>tractivity_db.view_events.latest_activity</code>.
     */
    public void setLatestActivity(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.latest_activity</code>.
     */
    public Timestamp getLatestActivity() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>tractivity_db.view_events.activities</code>.
     */
    public void setActivities(SimpleActivity[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>tractivity_db.view_events.activities</code>.
     */
    public SimpleActivity[] getActivities() {
        return (SimpleActivity[]) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Timestamp, Timestamp, SimpleActivity[]> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Timestamp, Timestamp, SimpleActivity[]> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewEvents.VIEW_EVENTS.EVENT_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewEvents.VIEW_EVENTS.EVENT_NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewEvents.VIEW_EVENTS.EVENT_DESCRIPTION;
    }

    @Override
    public Field<Timestamp> field4() {
        return ViewEvents.VIEW_EVENTS.EVENT_CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return ViewEvents.VIEW_EVENTS.LATEST_ACTIVITY;
    }

    @Override
    public Field<SimpleActivity[]> field6() {
        return ViewEvents.VIEW_EVENTS.ACTIVITIES;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public String component2() {
        return getEventName();
    }

    @Override
    public String component3() {
        return getEventDescription();
    }

    @Override
    public Timestamp component4() {
        return getEventCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getLatestActivity();
    }

    @Override
    public SimpleActivity[] component6() {
        return getActivities();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public String value2() {
        return getEventName();
    }

    @Override
    public String value3() {
        return getEventDescription();
    }

    @Override
    public Timestamp value4() {
        return getEventCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getLatestActivity();
    }

    @Override
    public SimpleActivity[] value6() {
        return getActivities();
    }

    @Override
    public ViewEventsRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public ViewEventsRecord value2(String value) {
        setEventName(value);
        return this;
    }

    @Override
    public ViewEventsRecord value3(String value) {
        setEventDescription(value);
        return this;
    }

    @Override
    public ViewEventsRecord value4(Timestamp value) {
        setEventCreatedOn(value);
        return this;
    }

    @Override
    public ViewEventsRecord value5(Timestamp value) {
        setLatestActivity(value);
        return this;
    }

    @Override
    public ViewEventsRecord value6(SimpleActivity[] value) {
        setActivities(value);
        return this;
    }

    @Override
    public ViewEventsRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5, SimpleActivity[] value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewEventsRecord
     */
    public ViewEventsRecord() {
        super(ViewEvents.VIEW_EVENTS);
    }

    /**
     * Create a detached, initialised ViewEventsRecord
     */
    public ViewEventsRecord(Integer eventId, String eventName, String eventDescription, Timestamp eventCreatedOn, Timestamp latestActivity, SimpleActivity[] activities) {
        super(ViewEvents.VIEW_EVENTS);

        setEventId(eventId);
        setEventName(eventName);
        setEventDescription(eventDescription);
        setEventCreatedOn(eventCreatedOn);
        setLatestActivity(latestActivity);
        setActivities(activities);
    }

    /**
     * Create a detached, initialised ViewEventsRecord
     */
    public ViewEventsRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.ViewEvents value) {
        super(ViewEvents.VIEW_EVENTS);

        if (value != null) {
            setEventId(value.getEventId());
            setEventName(value.getEventName());
            setEventDescription(value.getEventDescription());
            setEventCreatedOn(value.getEventCreatedOn());
            setLatestActivity(value.getLatestActivity());
            setActivities(value.getActivities());
        }
    }
    // @formatter:on
}
