/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.records;


import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;

import uk.co.raubach.tractivity.server.database.codegen.enums.ViewActivityMeasuresMeasureType;
import uk.co.raubach.tractivity.server.database.codegen.enums.ViewActivityMeasuresParticipantGender;
import uk.co.raubach.tractivity.server.database.codegen.tables.ViewActivityMeasures;
import uk.co.raubach.tractivity.server.pojo.MeasureRestrictions;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewActivityMeasuresRecord extends TableRecordImpl<ViewActivityMeasuresRecord> implements Record12<Integer, Integer, Integer, String, Integer, String, ViewActivityMeasuresParticipantGender, Integer, String, ViewActivityMeasuresMeasureType, MeasureRestrictions, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_measure_id</code>.
     */
    public void setActivityMeasureId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_measure_id</code>.
     */
    public Integer getActivityMeasureId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tractivity_db.view_activity_measures.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activity_measures.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_type_name</code>.
     */
    public void setActivityTypeName(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_type_name</code>.
     */
    public String getActivityTypeName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_id</code>.
     */
    public void setParticipantId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_id</code>.
     */
    public Integer getParticipantId() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_name</code>.
     */
    public void setParticipantName(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_name</code>.
     */
    public String getParticipantName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_gender</code>.
     */
    public void setParticipantGender(ViewActivityMeasuresParticipantGender value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_gender</code>.
     */
    public ViewActivityMeasuresParticipantGender getParticipantGender() {
        return (ViewActivityMeasuresParticipantGender) get(6);
    }

    /**
     * Setter for <code>tractivity_db.view_activity_measures.measure_id</code>.
     */
    public void setMeasureId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>tractivity_db.view_activity_measures.measure_id</code>.
     */
    public Integer getMeasureId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_name</code>.
     */
    public void setMeasureName(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_name</code>.
     */
    public String getMeasureName() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_type</code>.
     */
    public void setMeasureType(ViewActivityMeasuresMeasureType value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_type</code>.
     */
    public ViewActivityMeasuresMeasureType getMeasureType() {
        return (ViewActivityMeasuresMeasureType) get(9);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_restrictions</code>.
     */
    public void setMeasureRestrictions(MeasureRestrictions value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_restrictions</code>.
     */
    public MeasureRestrictions getMeasureRestrictions() {
        return (MeasureRestrictions) get(10);
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measured_value</code>.
     */
    public void setMeasuredValue(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measured_value</code>.
     */
    public String getMeasuredValue() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, Integer, String, Integer, String, ViewActivityMeasuresParticipantGender, Integer, String, ViewActivityMeasuresMeasureType, MeasureRestrictions, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, Integer, String, Integer, String, ViewActivityMeasuresParticipantGender, Integer, String, ViewActivityMeasuresMeasureType, MeasureRestrictions, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.ACTIVITY_MEASURE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.ACTIVITY_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.ACTIVITY_TYPE_ID;
    }

    @Override
    public Field<String> field4() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.ACTIVITY_TYPE_NAME;
    }

    @Override
    public Field<Integer> field5() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.PARTICIPANT_ID;
    }

    @Override
    public Field<String> field6() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.PARTICIPANT_NAME;
    }

    @Override
    public Field<ViewActivityMeasuresParticipantGender> field7() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.PARTICIPANT_GENDER;
    }

    @Override
    public Field<Integer> field8() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.MEASURE_ID;
    }

    @Override
    public Field<String> field9() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.MEASURE_NAME;
    }

    @Override
    public Field<ViewActivityMeasuresMeasureType> field10() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.MEASURE_TYPE;
    }

    @Override
    public Field<MeasureRestrictions> field11() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.MEASURE_RESTRICTIONS;
    }

    @Override
    public Field<String> field12() {
        return ViewActivityMeasures.VIEW_ACTIVITY_MEASURES.MEASURED_VALUE;
    }

    @Override
    public Integer component1() {
        return getActivityMeasureId();
    }

    @Override
    public Integer component2() {
        return getActivityId();
    }

    @Override
    public Integer component3() {
        return getActivityTypeId();
    }

    @Override
    public String component4() {
        return getActivityTypeName();
    }

    @Override
    public Integer component5() {
        return getParticipantId();
    }

    @Override
    public String component6() {
        return getParticipantName();
    }

    @Override
    public ViewActivityMeasuresParticipantGender component7() {
        return getParticipantGender();
    }

    @Override
    public Integer component8() {
        return getMeasureId();
    }

    @Override
    public String component9() {
        return getMeasureName();
    }

    @Override
    public ViewActivityMeasuresMeasureType component10() {
        return getMeasureType();
    }

    @Override
    public MeasureRestrictions component11() {
        return getMeasureRestrictions();
    }

    @Override
    public String component12() {
        return getMeasuredValue();
    }

    @Override
    public Integer value1() {
        return getActivityMeasureId();
    }

    @Override
    public Integer value2() {
        return getActivityId();
    }

    @Override
    public Integer value3() {
        return getActivityTypeId();
    }

    @Override
    public String value4() {
        return getActivityTypeName();
    }

    @Override
    public Integer value5() {
        return getParticipantId();
    }

    @Override
    public String value6() {
        return getParticipantName();
    }

    @Override
    public ViewActivityMeasuresParticipantGender value7() {
        return getParticipantGender();
    }

    @Override
    public Integer value8() {
        return getMeasureId();
    }

    @Override
    public String value9() {
        return getMeasureName();
    }

    @Override
    public ViewActivityMeasuresMeasureType value10() {
        return getMeasureType();
    }

    @Override
    public MeasureRestrictions value11() {
        return getMeasureRestrictions();
    }

    @Override
    public String value12() {
        return getMeasuredValue();
    }

    @Override
    public ViewActivityMeasuresRecord value1(Integer value) {
        setActivityMeasureId(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value2(Integer value) {
        setActivityId(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value3(Integer value) {
        setActivityTypeId(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value4(String value) {
        setActivityTypeName(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value5(Integer value) {
        setParticipantId(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value6(String value) {
        setParticipantName(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value7(ViewActivityMeasuresParticipantGender value) {
        setParticipantGender(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value8(Integer value) {
        setMeasureId(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value9(String value) {
        setMeasureName(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value10(ViewActivityMeasuresMeasureType value) {
        setMeasureType(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value11(MeasureRestrictions value) {
        setMeasureRestrictions(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord value12(String value) {
        setMeasuredValue(value);
        return this;
    }

    @Override
    public ViewActivityMeasuresRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, String value6, ViewActivityMeasuresParticipantGender value7, Integer value8, String value9, ViewActivityMeasuresMeasureType value10, MeasureRestrictions value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewActivityMeasuresRecord
     */
    public ViewActivityMeasuresRecord() {
        super(ViewActivityMeasures.VIEW_ACTIVITY_MEASURES);
    }

    /**
     * Create a detached, initialised ViewActivityMeasuresRecord
     */
    public ViewActivityMeasuresRecord(Integer activityMeasureId, Integer activityId, Integer activityTypeId, String activityTypeName, Integer participantId, String participantName, ViewActivityMeasuresParticipantGender participantGender, Integer measureId, String measureName, ViewActivityMeasuresMeasureType measureType, MeasureRestrictions measureRestrictions, String measuredValue) {
        super(ViewActivityMeasures.VIEW_ACTIVITY_MEASURES);

        setActivityMeasureId(activityMeasureId);
        setActivityId(activityId);
        setActivityTypeId(activityTypeId);
        setActivityTypeName(activityTypeName);
        setParticipantId(participantId);
        setParticipantName(participantName);
        setParticipantGender(participantGender);
        setMeasureId(measureId);
        setMeasureName(measureName);
        setMeasureType(measureType);
        setMeasureRestrictions(measureRestrictions);
        setMeasuredValue(measuredValue);
    }

    /**
     * Create a detached, initialised ViewActivityMeasuresRecord
     */
    public ViewActivityMeasuresRecord(uk.co.raubach.tractivity.server.database.codegen.tables.pojos.ViewActivityMeasures value) {
        super(ViewActivityMeasures.VIEW_ACTIVITY_MEASURES);

        if (value != null) {
            setActivityMeasureId(value.getActivityMeasureId());
            setActivityId(value.getActivityId());
            setActivityTypeId(value.getActivityTypeId());
            setActivityTypeName(value.getActivityTypeName());
            setParticipantId(value.getParticipantId());
            setParticipantName(value.getParticipantName());
            setParticipantGender(value.getParticipantGender());
            setMeasureId(value.getMeasureId());
            setMeasureName(value.getMeasureName());
            setMeasureType(value.getMeasureType());
            setMeasureRestrictions(value.getMeasureRestrictions());
            setMeasuredValue(value.getMeasuredValue());
        }
    }
    // @formatter:on
}
