/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.tractivity.server.database.codegen.TractivityDb;
import uk.co.raubach.tractivity.server.database.codegen.tables.records.ActivityTypesRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityTypes extends TableImpl<ActivityTypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tractivity_db.activity_types</code>
     */
    public static final ActivityTypes ACTIVITY_TYPES = new ActivityTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityTypesRecord> getRecordType() {
        return ActivityTypesRecord.class;
    }

    /**
     * The column <code>tractivity_db.activity_types.id</code>.
     */
    public final TableField<ActivityTypesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tractivity_db.activity_types.name</code>.
     */
    public final TableField<ActivityTypesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tractivity_db.activity_types.image</code>.
     */
    public final TableField<ActivityTypesRecord, byte[]> IMAGE = createField(DSL.name("image"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>tractivity_db.activity_types.created_on</code>.
     */
    public final TableField<ActivityTypesRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tractivity_db.activity_types.updated_on</code>.
     */
    public final TableField<ActivityTypesRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private ActivityTypes(Name alias, Table<ActivityTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActivityTypes(Name alias, Table<ActivityTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tractivity_db.activity_types</code> table
     * reference
     */
    public ActivityTypes(String alias) {
        this(DSL.name(alias), ACTIVITY_TYPES);
    }

    /**
     * Create an aliased <code>tractivity_db.activity_types</code> table
     * reference
     */
    public ActivityTypes(Name alias) {
        this(alias, ACTIVITY_TYPES);
    }

    /**
     * Create a <code>tractivity_db.activity_types</code> table reference
     */
    public ActivityTypes() {
        this(DSL.name("activity_types"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TractivityDb.TRACTIVITY_DB;
    }

    @Override
    public Identity<ActivityTypesRecord, Integer> getIdentity() {
        return (Identity<ActivityTypesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActivityTypesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(ActivityTypes.ACTIVITY_TYPES, DSL.name("KEY_activity_types_PRIMARY"), new TableField[] { ActivityTypes.ACTIVITY_TYPES.ID }, true);
    }

    @Override
    public ActivityTypes as(String alias) {
        return new ActivityTypes(DSL.name(alias), this);
    }

    @Override
    public ActivityTypes as(Name alias) {
        return new ActivityTypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityTypes rename(String name) {
        return new ActivityTypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityTypes rename(Name name) {
        return new ActivityTypes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, byte[], Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
    // @formatter:on
}
