/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.tractivity.server.database.codegen.TractivityDb;
import uk.co.raubach.tractivity.server.database.codegen.tables.records.ActivityMeasuresRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityMeasures extends TableImpl<ActivityMeasuresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tractivity_db.activity_measures</code>
     */
    public static final ActivityMeasures ACTIVITY_MEASURES = new ActivityMeasures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityMeasuresRecord> getRecordType() {
        return ActivityMeasuresRecord.class;
    }

    /**
     * The column <code>tractivity_db.activity_measures.id</code>.
     */
    public final TableField<ActivityMeasuresRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.activity_id</code>.
     */
    public final TableField<ActivityMeasuresRecord, Integer> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.participant_id</code>.
     */
    public final TableField<ActivityMeasuresRecord, Integer> PARTICIPANT_ID = createField(DSL.name("participant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.measure_id</code>.
     */
    public final TableField<ActivityMeasuresRecord, Integer> MEASURE_ID = createField(DSL.name("measure_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.measured_value</code>.
     */
    public final TableField<ActivityMeasuresRecord, String> MEASURED_VALUE = createField(DSL.name("measured_value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.created_on</code>.
     */
    public final TableField<ActivityMeasuresRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tractivity_db.activity_measures.updated_on</code>.
     */
    public final TableField<ActivityMeasuresRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private ActivityMeasures(Name alias, Table<ActivityMeasuresRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActivityMeasures(Name alias, Table<ActivityMeasuresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tractivity_db.activity_measures</code> table
     * reference
     */
    public ActivityMeasures(String alias) {
        this(DSL.name(alias), ACTIVITY_MEASURES);
    }

    /**
     * Create an aliased <code>tractivity_db.activity_measures</code> table
     * reference
     */
    public ActivityMeasures(Name alias) {
        this(alias, ACTIVITY_MEASURES);
    }

    /**
     * Create a <code>tractivity_db.activity_measures</code> table reference
     */
    public ActivityMeasures() {
        this(DSL.name("activity_measures"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TractivityDb.TRACTIVITY_DB;
    }

    @Override
    public Identity<ActivityMeasuresRecord, Integer> getIdentity() {
        return (Identity<ActivityMeasuresRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActivityMeasuresRecord> getPrimaryKey() {
        return Internal.createUniqueKey(ActivityMeasures.ACTIVITY_MEASURES, DSL.name("KEY_activity_measures_PRIMARY"), new TableField[] { ActivityMeasures.ACTIVITY_MEASURES.ID }, true);
    }

    @Override
    public ActivityMeasures as(String alias) {
        return new ActivityMeasures(DSL.name(alias), this);
    }

    @Override
    public ActivityMeasures as(Name alias) {
        return new ActivityMeasures(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityMeasures rename(String name) {
        return new ActivityMeasures(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityMeasures rename(Name name) {
        return new ActivityMeasures(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
    // @formatter:on
}
