/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.tractivity.server.database.binding.MeasureRestrictionsBinding;
import uk.co.raubach.tractivity.server.database.codegen.TractivityDb;
import uk.co.raubach.tractivity.server.database.codegen.enums.MeasuresType;
import uk.co.raubach.tractivity.server.database.codegen.tables.records.MeasuresRecord;
import uk.co.raubach.tractivity.server.pojo.MeasureRestrictions;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measures extends TableImpl<MeasuresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tractivity_db.measures</code>
     */
    public static final Measures MEASURES = new Measures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MeasuresRecord> getRecordType() {
        return MeasuresRecord.class;
    }

    /**
     * The column <code>tractivity_db.measures.id</code>.
     */
    public final TableField<MeasuresRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tractivity_db.measures.name</code>.
     */
    public final TableField<MeasuresRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tractivity_db.measures.type</code>.
     */
    public final TableField<MeasuresRecord, MeasuresType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(11).nullable(false).defaultValue(DSL.inline("text", SQLDataType.VARCHAR)).asEnumDataType(uk.co.raubach.tractivity.server.database.codegen.enums.MeasuresType.class), this, "");

    /**
     * The column <code>tractivity_db.measures.image</code>.
     */
    public final TableField<MeasuresRecord, byte[]> IMAGE = createField(DSL.name("image"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>tractivity_db.measures.restrictions</code>.
     */
    public final TableField<MeasuresRecord, MeasureRestrictions> RESTRICTIONS = createField(DSL.name("restrictions"), SQLDataType.JSON, this, "", new MeasureRestrictionsBinding());

    /**
     * The column <code>tractivity_db.measures.default_value</code>.
     */
    public final TableField<MeasuresRecord, String> DEFAULT_VALUE = createField(DSL.name("default_value"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tractivity_db.measures.created_on</code>.
     */
    public final TableField<MeasuresRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tractivity_db.measures.updated_on</code>.
     */
    public final TableField<MeasuresRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Measures(Name alias, Table<MeasuresRecord> aliased) {
        this(alias, aliased, null);
    }

    private Measures(Name alias, Table<MeasuresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tractivity_db.measures</code> table reference
     */
    public Measures(String alias) {
        this(DSL.name(alias), MEASURES);
    }

    /**
     * Create an aliased <code>tractivity_db.measures</code> table reference
     */
    public Measures(Name alias) {
        this(alias, MEASURES);
    }

    /**
     * Create a <code>tractivity_db.measures</code> table reference
     */
    public Measures() {
        this(DSL.name("measures"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TractivityDb.TRACTIVITY_DB;
    }

    @Override
    public Identity<MeasuresRecord, Integer> getIdentity() {
        return (Identity<MeasuresRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MeasuresRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Measures.MEASURES, DSL.name("KEY_measures_PRIMARY"), new TableField[] { Measures.MEASURES.ID }, true);
    }

    @Override
    public Measures as(String alias) {
        return new Measures(DSL.name(alias), this);
    }

    @Override
    public Measures as(Name alias) {
        return new Measures(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Measures rename(String name) {
        return new Measures(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Measures rename(Name name) {
        return new Measures(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, MeasuresType, byte[], MeasureRestrictions, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
    // @formatter:on
}
