/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.tractivity.server.database.codegen.TractivityDb;
import uk.co.raubach.tractivity.server.database.codegen.enums.ParticipantsGender;
import uk.co.raubach.tractivity.server.database.codegen.tables.records.ParticipantsRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participants extends TableImpl<ParticipantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tractivity_db.participants</code>
     */
    public static final Participants PARTICIPANTS = new Participants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParticipantsRecord> getRecordType() {
        return ParticipantsRecord.class;
    }

    /**
     * The column <code>tractivity_db.participants.id</code>.
     */
    public final TableField<ParticipantsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tractivity_db.participants.name</code>.
     */
    public final TableField<ParticipantsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tractivity_db.participants.dob</code>.
     */
    public final TableField<ParticipantsRecord, Timestamp> DOB = createField(DSL.name("dob"), SQLDataType.TIMESTAMP(0), this, "");

    /**
     * The column <code>tractivity_db.participants.gender</code>.
     */
    public final TableField<ParticipantsRecord, ParticipantsGender> GENDER = createField(DSL.name("gender"), SQLDataType.VARCHAR(6).asEnumDataType(uk.co.raubach.tractivity.server.database.codegen.enums.ParticipantsGender.class), this, "");

    /**
     * The column <code>tractivity_db.participants.image</code>.
     */
    public final TableField<ParticipantsRecord, byte[]> IMAGE = createField(DSL.name("image"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>tractivity_db.participants.created_on</code>.
     */
    public final TableField<ParticipantsRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tractivity_db.participants.updated_on</code>.
     */
    public final TableField<ParticipantsRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Participants(Name alias, Table<ParticipantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Participants(Name alias, Table<ParticipantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tractivity_db.participants</code> table reference
     */
    public Participants(String alias) {
        this(DSL.name(alias), PARTICIPANTS);
    }

    /**
     * Create an aliased <code>tractivity_db.participants</code> table reference
     */
    public Participants(Name alias) {
        this(alias, PARTICIPANTS);
    }

    /**
     * Create a <code>tractivity_db.participants</code> table reference
     */
    public Participants() {
        this(DSL.name("participants"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TractivityDb.TRACTIVITY_DB;
    }

    @Override
    public Identity<ParticipantsRecord, Integer> getIdentity() {
        return (Identity<ParticipantsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ParticipantsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Participants.PARTICIPANTS, DSL.name("KEY_participants_PRIMARY"), new TableField[] { Participants.PARTICIPANTS.ID }, true);
    }

    @Override
    public Participants as(String alias) {
        return new Participants(DSL.name(alias), this);
    }

    @Override
    public Participants as(Name alias) {
        return new Participants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Participants rename(String name) {
        return new Participants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Participants rename(Name name) {
        return new Participants(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, Timestamp, ParticipantsGender, byte[], Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
    // @formatter:on
}
