/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityMeasures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   activityId;
    private Integer   participantId;
    private Integer   measureId;
    private String    measuredValue;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ActivityMeasures() {}

    public ActivityMeasures(ActivityMeasures value) {
        this.id = value.id;
        this.activityId = value.activityId;
        this.participantId = value.participantId;
        this.measureId = value.measureId;
        this.measuredValue = value.measuredValue;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ActivityMeasures(
        Integer   id,
        Integer   activityId,
        Integer   participantId,
        Integer   measureId,
        String    measuredValue,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.activityId = activityId;
        this.participantId = participantId;
        this.measureId = measureId;
        this.measuredValue = measuredValue;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.activity_id</code>.
     */
    public Integer getActivityId() {
        return this.activityId;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.activity_id</code>.
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.participant_id</code>.
     */
    public Integer getParticipantId() {
        return this.participantId;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.participant_id</code>.
     */
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.measure_id</code>.
     */
    public Integer getMeasureId() {
        return this.measureId;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.measure_id</code>.
     */
    public void setMeasureId(Integer measureId) {
        this.measureId = measureId;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.measured_value</code>.
     */
    public String getMeasuredValue() {
        return this.measuredValue;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.measured_value</code>.
     */
    public void setMeasuredValue(String measuredValue) {
        this.measuredValue = measuredValue;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>tractivity_db.activity_measures.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>tractivity_db.activity_measures.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityMeasures (");

        sb.append(id);
        sb.append(", ").append(activityId);
        sb.append(", ").append(participantId);
        sb.append(", ").append(measureId);
        sb.append(", ").append(measuredValue);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
