/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityParticipants implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   activityId;
    private Integer   participantId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public ActivityParticipants() {}

    public ActivityParticipants(ActivityParticipants value) {
        this.activityId = value.activityId;
        this.participantId = value.participantId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public ActivityParticipants(
        Integer   activityId,
        Integer   participantId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.activityId = activityId;
        this.participantId = participantId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>tractivity_db.activity_participants.activity_id</code>.
     */
    public Integer getActivityId() {
        return this.activityId;
    }

    /**
     * Setter for <code>tractivity_db.activity_participants.activity_id</code>.
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * Getter for
     * <code>tractivity_db.activity_participants.participant_id</code>.
     */
    public Integer getParticipantId() {
        return this.participantId;
    }

    /**
     * Setter for
     * <code>tractivity_db.activity_participants.participant_id</code>.
     */
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }

    /**
     * Getter for <code>tractivity_db.activity_participants.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>tractivity_db.activity_participants.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>tractivity_db.activity_participants.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>tractivity_db.activity_participants.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityParticipants (");

        sb.append(activityId);
        sb.append(", ").append(participantId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
