/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activities implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   activityTypeId;
    private Integer   eventId;
    private Integer   locationId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Activities() {}

    public Activities(Activities value) {
        this.id = value.id;
        this.activityTypeId = value.activityTypeId;
        this.eventId = value.eventId;
        this.locationId = value.locationId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Activities(
        Integer   id,
        Integer   activityTypeId,
        Integer   eventId,
        Integer   locationId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.activityTypeId = activityTypeId;
        this.eventId = eventId;
        this.locationId = locationId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>tractivity_db.activities.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tractivity_db.activities.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>tractivity_db.activities.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return this.activityTypeId;
    }

    /**
     * Setter for <code>tractivity_db.activities.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    /**
     * Getter for <code>tractivity_db.activities.event_id</code>.
     */
    public Integer getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>tractivity_db.activities.event_id</code>.
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * Getter for <code>tractivity_db.activities.location_id</code>.
     */
    public Integer getLocationId() {
        return this.locationId;
    }

    /**
     * Setter for <code>tractivity_db.activities.location_id</code>.
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for <code>tractivity_db.activities.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>tractivity_db.activities.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>tractivity_db.activities.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>tractivity_db.activities.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Activities (");

        sb.append(id);
        sb.append(", ").append(activityTypeId);
        sb.append(", ").append(eventId);
        sb.append(", ").append(locationId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
