/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import uk.co.raubach.tractivity.server.database.codegen.enums.MeasuresType;
import uk.co.raubach.tractivity.server.pojo.MeasureRestrictions;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer             id;
    private String              name;
    private MeasuresType        type;
    private byte[]              image;
    private MeasureRestrictions restrictions;
    private Timestamp           createdOn;
    private Timestamp           updatedOn;

    public Measures() {}

    public Measures(Measures value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.image = value.image;
        this.restrictions = value.restrictions;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Measures(
        Integer             id,
        String              name,
        MeasuresType        type,
        byte[]              image,
        MeasureRestrictions restrictions,
        Timestamp           createdOn,
        Timestamp           updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.image = image;
        this.restrictions = restrictions;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>tractivity_db.measures.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tractivity_db.measures.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>tractivity_db.measures.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>tractivity_db.measures.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>tractivity_db.measures.type</code>.
     */
    public MeasuresType getType() {
        return this.type;
    }

    /**
     * Setter for <code>tractivity_db.measures.type</code>.
     */
    public void setType(MeasuresType type) {
        this.type = type;
    }

    /**
     * Getter for <code>tractivity_db.measures.image</code>.
     */
    public byte[] getImage() {
        return this.image;
    }

    /**
     * Setter for <code>tractivity_db.measures.image</code>.
     */
    public void setImage(byte[] image) {
        this.image = image;
    }

    /**
     * Getter for <code>tractivity_db.measures.restrictions</code>.
     */
    public MeasureRestrictions getRestrictions() {
        return this.restrictions;
    }

    /**
     * Setter for <code>tractivity_db.measures.restrictions</code>.
     */
    public void setRestrictions(MeasureRestrictions restrictions) {
        this.restrictions = restrictions;
    }

    /**
     * Getter for <code>tractivity_db.measures.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>tractivity_db.measures.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>tractivity_db.measures.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>tractivity_db.measures.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Measures (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(restrictions);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
