/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import uk.co.raubach.tractivity.server.database.codegen.enums.ParticipantsGender;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participants implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer            id;
    private String             name;
    private Timestamp          dob;
    private ParticipantsGender gender;
    private byte[]             image;
    private Timestamp          createdOn;
    private Timestamp          updatedOn;

    public Participants() {}

    public Participants(Participants value) {
        this.id = value.id;
        this.name = value.name;
        this.dob = value.dob;
        this.gender = value.gender;
        this.image = value.image;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Participants(
        Integer            id,
        String             name,
        Timestamp          dob,
        ParticipantsGender gender,
        byte[]             image,
        Timestamp          createdOn,
        Timestamp          updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.dob = dob;
        this.gender = gender;
        this.image = image;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>tractivity_db.participants.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tractivity_db.participants.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>tractivity_db.participants.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>tractivity_db.participants.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>tractivity_db.participants.dob</code>.
     */
    public Timestamp getDob() {
        return this.dob;
    }

    /**
     * Setter for <code>tractivity_db.participants.dob</code>.
     */
    public void setDob(Timestamp dob) {
        this.dob = dob;
    }

    /**
     * Getter for <code>tractivity_db.participants.gender</code>.
     */
    public ParticipantsGender getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>tractivity_db.participants.gender</code>.
     */
    public void setGender(ParticipantsGender gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>tractivity_db.participants.image</code>.
     */
    public byte[] getImage() {
        return this.image;
    }

    /**
     * Setter for <code>tractivity_db.participants.image</code>.
     */
    public void setImage(byte[] image) {
        this.image = image;
    }

    /**
     * Getter for <code>tractivity_db.participants.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>tractivity_db.participants.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>tractivity_db.participants.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>tractivity_db.participants.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Participants (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dob);
        sb.append(", ").append(gender);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
