/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaVersion implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   installedRank;
    private String    version;
    private String    description;
    private String    type;
    private String    script;
    private Integer   checksum;
    private String    installedBy;
    private Timestamp installedOn;
    private Integer   executionTime;
    private Boolean   success;

    public SchemaVersion() {}

    public SchemaVersion(SchemaVersion value) {
        this.installedRank = value.installedRank;
        this.version = value.version;
        this.description = value.description;
        this.type = value.type;
        this.script = value.script;
        this.checksum = value.checksum;
        this.installedBy = value.installedBy;
        this.installedOn = value.installedOn;
        this.executionTime = value.executionTime;
        this.success = value.success;
    }

    public SchemaVersion(
        Integer   installedRank,
        String    version,
        String    description,
        String    type,
        String    script,
        Integer   checksum,
        String    installedBy,
        Timestamp installedOn,
        Integer   executionTime,
        Boolean   success
    ) {
        this.installedRank = installedRank;
        this.version = version;
        this.description = description;
        this.type = type;
        this.script = script;
        this.checksum = checksum;
        this.installedBy = installedBy;
        this.installedOn = installedOn;
        this.executionTime = executionTime;
        this.success = success;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.installed_rank</code>.
     */
    public Integer getInstalledRank() {
        return this.installedRank;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.installed_rank</code>.
     */
    public void setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.version</code>.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.version</code>.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.script</code>.
     */
    public String getScript() {
        return this.script;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.script</code>.
     */
    public void setScript(String script) {
        this.script = script;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.checksum</code>.
     */
    public Integer getChecksum() {
        return this.checksum;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.checksum</code>.
     */
    public void setChecksum(Integer checksum) {
        this.checksum = checksum;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.installed_by</code>.
     */
    public String getInstalledBy() {
        return this.installedBy;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.installed_by</code>.
     */
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.installed_on</code>.
     */
    public Timestamp getInstalledOn() {
        return this.installedOn;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.installed_on</code>.
     */
    public void setInstalledOn(Timestamp installedOn) {
        this.installedOn = installedOn;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.execution_time</code>.
     */
    public Integer getExecutionTime() {
        return this.executionTime;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.execution_time</code>.
     */
    public void setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * Getter for <code>tractivity_db.schema_version.success</code>.
     */
    public Boolean getSuccess() {
        return this.success;
    }

    /**
     * Setter for <code>tractivity_db.schema_version.success</code>.
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SchemaVersion (");

        sb.append(installedRank);
        sb.append(", ").append(version);
        sb.append(", ").append(description);
        sb.append(", ").append(type);
        sb.append(", ").append(script);
        sb.append(", ").append(checksum);
        sb.append(", ").append(installedBy);
        sb.append(", ").append(installedOn);
        sb.append(", ").append(executionTime);
        sb.append(", ").append(success);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
