/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;

import uk.co.raubach.tractivity.server.database.codegen.enums.ViewActivityMeasuresMeasureType;
import uk.co.raubach.tractivity.server.database.codegen.enums.ViewActivityMeasuresParticipantGender;
import uk.co.raubach.tractivity.server.pojo.MeasureRestrictions;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewActivityMeasures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer                               activityMeasureId;
    private Integer                               activityId;
    private Integer                               activityTypeId;
    private String                                activityTypeName;
    private Integer                               participantId;
    private String                                participantName;
    private ViewActivityMeasuresParticipantGender participantGender;
    private Integer                               measureId;
    private String                                measureName;
    private ViewActivityMeasuresMeasureType       measureType;
    private MeasureRestrictions                   measureRestrictions;
    private String                                measuredValue;

    public ViewActivityMeasures() {}

    public ViewActivityMeasures(ViewActivityMeasures value) {
        this.activityMeasureId = value.activityMeasureId;
        this.activityId = value.activityId;
        this.activityTypeId = value.activityTypeId;
        this.activityTypeName = value.activityTypeName;
        this.participantId = value.participantId;
        this.participantName = value.participantName;
        this.participantGender = value.participantGender;
        this.measureId = value.measureId;
        this.measureName = value.measureName;
        this.measureType = value.measureType;
        this.measureRestrictions = value.measureRestrictions;
        this.measuredValue = value.measuredValue;
    }

    public ViewActivityMeasures(
        Integer                               activityMeasureId,
        Integer                               activityId,
        Integer                               activityTypeId,
        String                                activityTypeName,
        Integer                               participantId,
        String                                participantName,
        ViewActivityMeasuresParticipantGender participantGender,
        Integer                               measureId,
        String                                measureName,
        ViewActivityMeasuresMeasureType       measureType,
        MeasureRestrictions                   measureRestrictions,
        String                                measuredValue
    ) {
        this.activityMeasureId = activityMeasureId;
        this.activityId = activityId;
        this.activityTypeId = activityTypeId;
        this.activityTypeName = activityTypeName;
        this.participantId = participantId;
        this.participantName = participantName;
        this.participantGender = participantGender;
        this.measureId = measureId;
        this.measureName = measureName;
        this.measureType = measureType;
        this.measureRestrictions = measureRestrictions;
        this.measuredValue = measuredValue;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_measure_id</code>.
     */
    public Integer getActivityMeasureId() {
        return this.activityMeasureId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_measure_id</code>.
     */
    public void setActivityMeasureId(Integer activityMeasureId) {
        this.activityMeasureId = activityMeasureId;
    }

    /**
     * Getter for <code>tractivity_db.view_activity_measures.activity_id</code>.
     */
    public Integer getActivityId() {
        return this.activityId;
    }

    /**
     * Setter for <code>tractivity_db.view_activity_measures.activity_id</code>.
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return this.activityTypeId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.activity_type_name</code>.
     */
    public String getActivityTypeName() {
        return this.activityTypeName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.activity_type_name</code>.
     */
    public void setActivityTypeName(String activityTypeName) {
        this.activityTypeName = activityTypeName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_id</code>.
     */
    public Integer getParticipantId() {
        return this.participantId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_id</code>.
     */
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_name</code>.
     */
    public String getParticipantName() {
        return this.participantName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_name</code>.
     */
    public void setParticipantName(String participantName) {
        this.participantName = participantName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.participant_gender</code>.
     */
    public ViewActivityMeasuresParticipantGender getParticipantGender() {
        return this.participantGender;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.participant_gender</code>.
     */
    public void setParticipantGender(ViewActivityMeasuresParticipantGender participantGender) {
        this.participantGender = participantGender;
    }

    /**
     * Getter for <code>tractivity_db.view_activity_measures.measure_id</code>.
     */
    public Integer getMeasureId() {
        return this.measureId;
    }

    /**
     * Setter for <code>tractivity_db.view_activity_measures.measure_id</code>.
     */
    public void setMeasureId(Integer measureId) {
        this.measureId = measureId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_name</code>.
     */
    public String getMeasureName() {
        return this.measureName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_name</code>.
     */
    public void setMeasureName(String measureName) {
        this.measureName = measureName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_type</code>.
     */
    public ViewActivityMeasuresMeasureType getMeasureType() {
        return this.measureType;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_type</code>.
     */
    public void setMeasureType(ViewActivityMeasuresMeasureType measureType) {
        this.measureType = measureType;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measure_restrictions</code>.
     */
    public MeasureRestrictions getMeasureRestrictions() {
        return this.measureRestrictions;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measure_restrictions</code>.
     */
    public void setMeasureRestrictions(MeasureRestrictions measureRestrictions) {
        this.measureRestrictions = measureRestrictions;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_measures.measured_value</code>.
     */
    public String getMeasuredValue() {
        return this.measuredValue;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_measures.measured_value</code>.
     */
    public void setMeasuredValue(String measuredValue) {
        this.measuredValue = measuredValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewActivityMeasures (");

        sb.append(activityMeasureId);
        sb.append(", ").append(activityId);
        sb.append(", ").append(activityTypeId);
        sb.append(", ").append(activityTypeName);
        sb.append(", ").append(participantId);
        sb.append(", ").append(participantName);
        sb.append(", ").append(participantGender);
        sb.append(", ").append(measureId);
        sb.append(", ").append(measureName);
        sb.append(", ").append(measureType);
        sb.append(", ").append(measureRestrictions);
        sb.append(", ").append(measuredValue);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
