/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;

import uk.co.raubach.tractivity.server.pojo.SimpleActivity;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer          eventId;
    private String           eventName;
    private String           eventDescription;
    private Timestamp        eventCreatedOn;
    private Timestamp        latestActivity;
    private SimpleActivity[] activities;

    public ViewEvents() {}

    public ViewEvents(ViewEvents value) {
        this.eventId = value.eventId;
        this.eventName = value.eventName;
        this.eventDescription = value.eventDescription;
        this.eventCreatedOn = value.eventCreatedOn;
        this.latestActivity = value.latestActivity;
        this.activities = value.activities;
    }

    public ViewEvents(
        Integer          eventId,
        String           eventName,
        String           eventDescription,
        Timestamp        eventCreatedOn,
        Timestamp        latestActivity,
        SimpleActivity[] activities
    ) {
        this.eventId = eventId;
        this.eventName = eventName;
        this.eventDescription = eventDescription;
        this.eventCreatedOn = eventCreatedOn;
        this.latestActivity = latestActivity;
        this.activities = activities;
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_id</code>.
     */
    public Integer getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_id</code>.
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_name</code>.
     */
    public String getEventName() {
        return this.eventName;
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_name</code>.
     */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_description</code>.
     */
    public String getEventDescription() {
        return this.eventDescription;
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_description</code>.
     */
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    /**
     * Getter for <code>tractivity_db.view_events.event_created_on</code>.
     */
    public Timestamp getEventCreatedOn() {
        return this.eventCreatedOn;
    }

    /**
     * Setter for <code>tractivity_db.view_events.event_created_on</code>.
     */
    public void setEventCreatedOn(Timestamp eventCreatedOn) {
        this.eventCreatedOn = eventCreatedOn;
    }

    /**
     * Getter for <code>tractivity_db.view_events.latest_activity</code>.
     */
    public Timestamp getLatestActivity() {
        return this.latestActivity;
    }

    /**
     * Setter for <code>tractivity_db.view_events.latest_activity</code>.
     */
    public void setLatestActivity(Timestamp latestActivity) {
        this.latestActivity = latestActivity;
    }

    /**
     * Getter for <code>tractivity_db.view_events.activities</code>.
     */
    public SimpleActivity[] getActivities() {
        return this.activities;
    }

    /**
     * Setter for <code>tractivity_db.view_events.activities</code>.
     */
    public void setActivities(SimpleActivity[] activities) {
        this.activities = activities;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewEvents (");

        sb.append(eventId);
        sb.append(", ").append(eventName);
        sb.append(", ").append(eventDescription);
        sb.append(", ").append(eventCreatedOn);
        sb.append(", ").append(latestActivity);
        sb.append(", ").append(Arrays.toString(activities));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
