/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.tractivity.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;

import uk.co.raubach.tractivity.server.pojo.ParticipantMeasures;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewActivityParticipantMeasures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer               activityId;
    private Integer               activityTypeId;
    private String                activityTypeName;
    private Timestamp             activityCreatedOn;
    private Integer               eventId;
    private String                eventName;
    private Timestamp             eventCreatedOn;
    private Integer               locationId;
    private String                locationName;
    private BigDecimal            locationLatitude;
    private BigDecimal            locationLongitude;
    private BigDecimal            locationElevation;
    private ParticipantMeasures[] participantMeasures;

    public ViewActivityParticipantMeasures() {}

    public ViewActivityParticipantMeasures(ViewActivityParticipantMeasures value) {
        this.activityId = value.activityId;
        this.activityTypeId = value.activityTypeId;
        this.activityTypeName = value.activityTypeName;
        this.activityCreatedOn = value.activityCreatedOn;
        this.eventId = value.eventId;
        this.eventName = value.eventName;
        this.eventCreatedOn = value.eventCreatedOn;
        this.locationId = value.locationId;
        this.locationName = value.locationName;
        this.locationLatitude = value.locationLatitude;
        this.locationLongitude = value.locationLongitude;
        this.locationElevation = value.locationElevation;
        this.participantMeasures = value.participantMeasures;
    }

    public ViewActivityParticipantMeasures(
        Integer               activityId,
        Integer               activityTypeId,
        String                activityTypeName,
        Timestamp             activityCreatedOn,
        Integer               eventId,
        String                eventName,
        Timestamp             eventCreatedOn,
        Integer               locationId,
        String                locationName,
        BigDecimal            locationLatitude,
        BigDecimal            locationLongitude,
        BigDecimal            locationElevation,
        ParticipantMeasures[] participantMeasures
    ) {
        this.activityId = activityId;
        this.activityTypeId = activityTypeId;
        this.activityTypeName = activityTypeName;
        this.activityCreatedOn = activityCreatedOn;
        this.eventId = eventId;
        this.eventName = eventName;
        this.eventCreatedOn = eventCreatedOn;
        this.locationId = locationId;
        this.locationName = locationName;
        this.locationLatitude = locationLatitude;
        this.locationLongitude = locationLongitude;
        this.locationElevation = locationElevation;
        this.participantMeasures = participantMeasures;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_id</code>.
     */
    public Integer getActivityId() {
        return this.activityId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_id</code>.
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_id</code>.
     */
    public Integer getActivityTypeId() {
        return this.activityTypeId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_id</code>.
     */
    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_name</code>.
     */
    public String getActivityTypeName() {
        return this.activityTypeName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_type_name</code>.
     */
    public void setActivityTypeName(String activityTypeName) {
        this.activityTypeName = activityTypeName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.activity_created_on</code>.
     */
    public Timestamp getActivityCreatedOn() {
        return this.activityCreatedOn;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.activity_created_on</code>.
     */
    public void setActivityCreatedOn(Timestamp activityCreatedOn) {
        this.activityCreatedOn = activityCreatedOn;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_id</code>.
     */
    public Integer getEventId() {
        return this.eventId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_id</code>.
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_name</code>.
     */
    public String getEventName() {
        return this.eventName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_name</code>.
     */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.event_created_on</code>.
     */
    public Timestamp getEventCreatedOn() {
        return this.eventCreatedOn;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.event_created_on</code>.
     */
    public void setEventCreatedOn(Timestamp eventCreatedOn) {
        this.eventCreatedOn = eventCreatedOn;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_id</code>.
     */
    public Integer getLocationId() {
        return this.locationId;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_id</code>.
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_name</code>.
     */
    public String getLocationName() {
        return this.locationName;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_name</code>.
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_latitude</code>.
     */
    public BigDecimal getLocationLatitude() {
        return this.locationLatitude;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_latitude</code>.
     */
    public void setLocationLatitude(BigDecimal locationLatitude) {
        this.locationLatitude = locationLatitude;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_longitude</code>.
     */
    public BigDecimal getLocationLongitude() {
        return this.locationLongitude;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_longitude</code>.
     */
    public void setLocationLongitude(BigDecimal locationLongitude) {
        this.locationLongitude = locationLongitude;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.location_elevation</code>.
     */
    public BigDecimal getLocationElevation() {
        return this.locationElevation;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.location_elevation</code>.
     */
    public void setLocationElevation(BigDecimal locationElevation) {
        this.locationElevation = locationElevation;
    }

    /**
     * Getter for
     * <code>tractivity_db.view_activity_participant_measures.participant_measures</code>.
     */
    public ParticipantMeasures[] getParticipantMeasures() {
        return this.participantMeasures;
    }

    /**
     * Setter for
     * <code>tractivity_db.view_activity_participant_measures.participant_measures</code>.
     */
    public void setParticipantMeasures(ParticipantMeasures[] participantMeasures) {
        this.participantMeasures = participantMeasures;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewActivityParticipantMeasures (");

        sb.append(activityId);
        sb.append(", ").append(activityTypeId);
        sb.append(", ").append(activityTypeName);
        sb.append(", ").append(activityCreatedOn);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventName);
        sb.append(", ").append(eventCreatedOn);
        sb.append(", ").append(locationId);
        sb.append(", ").append(locationName);
        sb.append(", ").append(locationLatitude);
        sb.append(", ").append(locationLongitude);
        sb.append(", ").append(locationElevation);
        sb.append(", ").append(Arrays.toString(participantMeasures));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
